// Read-only integration input: actual issued catalog/item, never fabricated business rows.
// Requires the local API; browser QA remains separate.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const nodes = new Map(), etaInputs = [];
function node(id) {
  if (!nodes.has(id)) nodes.set(id, {value:'',checked:false,textContent:'',innerHTML:'',hidden:false,disabled:false,elements:{},dataset:{},addEventListener(){},setAttribute(){},removeAttribute(){},classList:{toggle(){}}});
  return nodes.get(id);
}
let postCalls = 0, checks = 0;
const check = (fn) => {fn();checks++;};
const context = vm.createContext({console,Intl,AbortController,Map,Number,URL,setTimeout,requestAnimationFrame(){},window:{addEventListener(){},scrollTo(){}},document:{getElementById:node,addEventListener(){},querySelectorAll:(selector)=>selector === '[data-eta]' ? etaInputs : []},fetch(){postCalls++;throw Error('No app request expected');}});
const run=(code)=>vm.runInContext(code,context);
vm.runInContext(fs.readFileSync(__dirname+'/../web/app.js','utf8').replace(/renderDraft\(\); loadBootstrap\(\);\s*$/, ''),context);
for(const key of ['lead_days','cover_days','safety_days','moq','method','use_reported_stock','regular_only']) node('policy-form').elements[key]={value:'',checked:false};
node('policy-form').reset=()=>{for(const input of Object.values(node('policy-form').elements)){input.value='';input.checked=false;}etaInputs.forEach((input)=>{input.value='';});};
(async()=>{
  const bootstrap=await (await fetch('http://127.0.0.1:8765/api/bootstrap')).json();
  const payload=await (await fetch('http://127.0.0.1:8765/api/item?key=SystemElectric%3A%3AATN540126')).json();
  context.issued=payload.item;context.bootstrap=bootstrap;
  const original=JSON.stringify(payload.item);
  run('state.bootstrap=bootstrap;state.item=issued;state.key="SystemElectric::ATN540126"');
  check(()=>assert.equal(run('knownDataRows(issued).find(([k])=>k.startsWith("Свободно"))[1]'),'23'));
  check(()=>assert.equal(run('demoEtaFor(issued,0)'),'2026-10-08'));
  check(()=>assert.equal(run('demoEtaFor(issued,1)'),null));
  etaInputs.push({dataset:{eta:'0'},value:''});
  node('policy-form').elements.use_reported_stock.checked=true;
  node('policy-form').elements.regular_only.checked=true;
  run('state.drafts.set(state.key,{result_id:"obsolete"});state.drafts.set("other::sku",{result_id:"other",item:{supplier:"other"},order:{}});applyDemoPreset()');
  check(()=>assert.equal(run('state.demo'),true));
  check(()=>assert.equal(run('readPolicy().scenario_mode'),'demonstration'));
  check(()=>assert.equal(node('policy-form').elements.lead_days.value,'2'));
  check(()=>assert.equal(node('policy-form').elements.cover_days.value,'30'));
  check(()=>assert.equal(node('policy-form').elements.safety_days.value,'7'));
  check(()=>assert.equal(node('policy-form').elements.moq.value,'0'));
  check(()=>assert.equal(node('policy-form').elements.use_reported_stock.checked,false));
  check(()=>assert.equal(node('policy-form').elements.regular_only.checked,false));
  check(()=>assert.equal(etaInputs[0].value,'2026-10-08'));
  check(()=>assert.equal(run('state.drafts.has(state.key)'),false));
  check(()=>assert.equal(run('state.drafts.has("other::sku")'),true));
  check(()=>assert.equal(run('state.plan'),null));
  check(()=>assert.equal(postCalls,0));
  check(()=>assert.equal(JSON.stringify(payload.item),original));
  check(()=>assert.match(node('demo-note').textContent,/Демонстрационные/));
  check(()=>assert.match(node('recommendation').innerHTML,/расчёт ещё не выполнен/));
  run('resetPolicy(true)');
  check(()=>assert.equal(run('state.demo'),false));
  check(()=>assert.equal(run('readPolicy().scenario_mode'),'manual'));
  check(()=>assert.equal(node('policy-form').elements.lead_days.value,''));
  check(()=>assert.equal(node('policy-form').elements.moq.value,''));
  check(()=>assert.equal(node('demo-note').hidden,true));
  const iek=bootstrap.items.find(item=>item.supplier==='IEK' && item.moq > 0 && item.stock.free == null);
  assert.ok(iek);context.iek=iek;
  run('state.item=iek;state.key=iek.key;applyDemoPreset()');
  check(()=>assert.equal(node('policy-form').elements.moq.value,String(iek.moq)));
  check(()=>assert.equal(run('knownDataRows(iek).find(([k])=>k.startsWith("Свободно"))[1]'),'Нет данных'));
  check(()=>assert.equal(run('demoEtaFor(iek,0)'),null));
  run('resetPolicy(true)');
  check(()=>assert.equal(String(node('policy-form').elements.moq.value),String(iek.moq)));
  run('state.item=issued;state.plan={item:issued,status:"blocked",order:{},policy:{scenario_mode:"demonstration"}};renderRecommendation()');
  check(()=>assert.match(node('recommendation').innerHTML,/Демонстрационный сценарий/));
  run('state.drafts.clear();state.drafts.set(state.key,state.plan);renderDraft()');
  check(()=>assert.match(node('draft').innerHTML,/демонстрационные сценарии/));
  run('renderDemandAdjustment(null)');
  check(()=>assert.equal(node('demand-section').hidden,true));
  check(()=>assert.equal(node('demand-table').innerHTML,''));
  console.log(`PASS: ${checks} demo/source-preservation checks; no app POST or source mutation.`);
})().catch(error=>{console.error(error);process.exitCode=1;});
